title: Ade Pitra Hermawan # your name (or website title) here
logo: "/images/ade.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! I am 25 years old master engineering graduate with over 2 years of working experience.
  <br><br>
  Currently living in South Korea 
  <br><br>
  <a href="https://kr.linkedin.com/in/pitrawan">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
